package com.exe202.skillnest.dto;

import com.exe202.skillnest.enums.RatingStatus;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RatingDTO {
    private Long ratingId;
    private Long contractId;
    private String projectTitle;
    private Long reviewerId;
    private String reviewerName;
    private Long revieweeId;
    private String revieweeName;
    private Integer score;
    private String comment;
    private RatingStatus status;
    private Boolean isAutoGenerated;
    private String adminNote;
    private LocalDateTime createdAt;
}
