package com.exe202.skillnest.mapper;

import com.exe202.skillnest.dto.RatingDTO;
import com.exe202.skillnest.entity.Rating;
import org.springframework.stereotype.Component;

@Component
public class RatingMapper {
    public RatingDTO toDTO(Rating entity) {
        if (entity == null) return null;
        return RatingDTO.builder()
                .ratingId(entity.getRatingId())
                .contractId(entity.getContract().getContractId())
                .projectTitle(entity.getContract().getProject().getTitle())
                .reviewerId(entity.getReviewer().getUserId())
                .reviewerName(entity.getReviewer().getFullName())
                .revieweeId(entity.getReviewee().getUserId())
                .revieweeName(entity.getReviewee().getFullName())
                .score(entity.getScore())
                .comment(entity.getComment())
                .status(entity.getStatus())
                .isAutoGenerated(entity.getIsAutoGenerated())
                .adminNote(entity.getAdminNote())
                .createdAt(entity.getCreatedAt())
                .build();
    }
}
