package com.exe202.skillnest.enums;

public enum NotificationType {
    NEW_PROPOSAL,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    PAYMENT_CREATED,
    PAYMENT_VERIFIED,
    PAYMENT_EXPIRED,
    CONTRACT_CREATED,
    CONTRACT_COMPLETED,
    CONTRACT_CANCELLED,
    NEW_MESSAGE,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    NEW_RATING,
    SUBSCRIPTION_ACTIVATED,
    AI_MATCH_INVITATION
}
