package com.exe202.skillnest.service.impl;

import com.exe202.skillnest.dto.CreateRatingRequest;
import com.exe202.skillnest.dto.RatingDTO;
import com.exe202.skillnest.dto.UserRatingStatsDTO;
import com.exe202.skillnest.entity.Contract;
import com.exe202.skillnest.entity.Rating;
import com.exe202.skillnest.entity.User;
import com.exe202.skillnest.enums.ContractStatus;
import com.exe202.skillnest.enums.RatingStatus;
import com.exe202.skillnest.exception.BadRequestException;
import com.exe202.skillnest.exception.ConflictException;
import com.exe202.skillnest.exception.ForbiddenException;
import com.exe202.skillnest.exception.NotFoundException;
import com.exe202.skillnest.mapper.RatingMapper;
import com.exe202.skillnest.repository.ContractRepository;
import com.exe202.skillnest.repository.RatingRepository;
import com.exe202.skillnest.repository.UserRepository;
import com.exe202.skillnest.service.RatingService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class RatingServiceImpl implements RatingService {

    private final RatingRepository ratingRepository;
    private final ContractRepository contractRepository;
    private final UserRepository userRepository;
    private final RatingMapper ratingMapper;
    private final com.exe202.skillnest.service.NotificationService notificationService;

    private static final int RATING_DEADLINE_DAYS = 30;

    @Override
    @Transactional
    public RatingDTO createRating(CreateRatingRequest request, String email) {
        User reviewer = userRepository.findByEmail(email)
                .orElseThrow(() -> new NotFoundException("User not found"));

        Contract contract = contractRepository.findById(request.getContractId())
                .orElseThrow(() -> new NotFoundException("Contract not found"));

        // 1. Contract must be COMPLETED
        if (contract.getStatus() != ContractStatus.COMPLETED) {
            throw new BadRequestException("Can only rate after contract is completed");
        }

        // 2. Check 30-day deadline
        if (contract.getEndAt() != null &&
            contract.getEndAt().plusDays(RATING_DEADLINE_DAYS).isBefore(LocalDateTime.now())) {
            throw new BadRequestException("Rating period expired. You had 30 days after contract completion to rate.");
        }

        // 3. Reviewer must be a participant
        boolean isClient = contract.getClient().getUserId().equals(reviewer.getUserId());
        boolean isStudent = contract.getStudent().getUserId().equals(reviewer.getUserId());
        if (!isClient && !isStudent) {
            throw new ForbiddenException("Only contract participants can rate");
        }

        // 4. Cannot rate twice
        if (ratingRepository.existsByContract_ContractIdAndReviewer_UserId(
                contract.getContractId(), reviewer.getUserId())) {
            throw new ConflictException("You have already rated for this contract");
        }

        // 5. Determine reviewee
        User reviewee = isClient ? contract.getStudent() : contract.getClient();

        // 6. Save rating
        Rating rating = Rating.builder()
                .contract(contract)
                .reviewer(reviewer)
                .reviewee(reviewee)
                .score(request.getScore())
                .comment(request.getComment())
                .status(RatingStatus.HIDDEN)
                .isAutoGenerated(false)
                .build();

        rating = ratingRepository.save(rating);
        log.info("Rating created: reviewer={} reviewee={} contract={} score={}",
                reviewer.getUserId(), reviewee.getUserId(), contract.getContractId(), request.getScore());

        // 7. Check if both parties have rated — apply visibility rules
        applyVisibilityRules(contract.getContractId());

        return ratingMapper.toDTO(rating);
    }

    /**
     * Visibility rules after both parties have rated:
     * - Both >= 4 stars: auto-reveal immediately
     * - Any < 4 stars: PENDING_REVIEW for admin
     * - Any <= 2 stars: PENDING_REVIEW + urgent log
     */
    private void applyVisibilityRules(Long contractId) {
        List<Rating> contractRatings = ratingRepository.findByContract_ContractId(contractId);
        if (contractRatings.size() < 2) return; // Wait for both parties

        boolean hasLowRating = contractRatings.stream()
                .filter(r -> !r.getIsAutoGenerated())
                .anyMatch(r -> r.getScore() < 4);
        boolean hasVeryLowRating = contractRatings.stream()
                .filter(r -> !r.getIsAutoGenerated())
                .anyMatch(r -> r.getScore() <= 2);

        if (!hasLowRating) {
            // Both >= 4 stars (or auto-generated): reveal immediately
            LocalDateTime now = LocalDateTime.now();
            for (Rating r : contractRatings) {
                if (r.getStatus() == RatingStatus.HIDDEN) {
                    r.setStatus(RatingStatus.VISIBLE);
                    r.setVisibleAt(now);
                    ratingRepository.save(r);
                }
            }
            log.info("All ratings >= 4 stars for contract {}. Auto-revealed.", contractId);

            // Notify both parties that ratings are now visible
            for (Rating r : contractRatings) {
                notificationService.notify(
                        r.getReviewee().getUserId(),
                        com.exe202.skillnest.enums.NotificationType.NEW_RATING,
                        "New rating received",
                        r.getReviewer().getFullName() + " rated you " + r.getScore() + " stars",
                        "RATING",
                        r.getRatingId()
                );
            }
        } else {
            // At least one real < 4 stars: admin review needed
            for (Rating r : contractRatings) {
                if (r.getStatus() == RatingStatus.HIDDEN) {
                    r.setStatus(RatingStatus.PENDING_REVIEW);
                    ratingRepository.save(r);
                }
            }
            if (hasVeryLowRating) {
                log.warn("URGENT: Rating <= 2 stars for contract {}. Priority admin review needed.", contractId);
            } else {
                log.info("Rating < 4 stars for contract {}. Sent to admin review.", contractId);
            }
        }
    }

    @Override
    @Transactional(readOnly = true)
    public Page<RatingDTO> getUserRatings(Long userId, Pageable pageable) {
        if (!userRepository.existsById(userId)) {
            throw new NotFoundException("User not found");
        }
        return ratingRepository.findVisibleByRevieweeId(userId, pageable)
                .map(ratingMapper::toDTO);
    }

    @Override
    @Transactional(readOnly = true)
    public List<RatingDTO> getContractRatings(Long contractId, String email) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new NotFoundException("User not found"));

        contractRepository.findByContractIdAndParticipant(contractId, user.getUserId())
                .orElseThrow(() -> new NotFoundException("Contract not found or you don't have access"));

        List<Rating> ratings = ratingRepository.findByContract_ContractId(contractId);

        return ratings.stream()
                .map(r -> {
                    RatingDTO dto = ratingMapper.toDTO(r);
                    boolean isMyRating = r.getReviewer().getUserId().equals(user.getUserId());
                    boolean isPublic = r.getStatus() == RatingStatus.VISIBLE || r.getStatus() == RatingStatus.APPROVED;

                    if (!isMyRating && !isPublic) {
                        dto.setScore(null);
                        dto.setComment("[Rating pending - visible after admin review or 7 days]");
                    }
                    return dto;
                })
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public Page<RatingDTO> getMyReceivedRatings(String email, Pageable pageable) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new NotFoundException("User not found"));
        return ratingRepository.findVisibleByRevieweeId(user.getUserId(), pageable)
                .map(ratingMapper::toDTO);
    }

    @Override
    @Transactional(readOnly = true)
    public UserRatingStatsDTO getUserRatingStats(Long userId) {
        if (!userRepository.existsById(userId)) {
            throw new NotFoundException("User not found");
        }

        Double avg = ratingRepository.findAverageScoreByRevieweeId(userId);
        Integer total = ratingRepository.countVisibleByRevieweeId(userId);

        return UserRatingStatsDTO.builder()
                .averageRating(avg)
                .totalReviews(total != null ? total : 0)
                .fiveStarCount(ratingRepository.countByRevieweeIdAndScore(userId, 5))
                .fourStarCount(ratingRepository.countByRevieweeIdAndScore(userId, 4))
                .threeStarCount(ratingRepository.countByRevieweeIdAndScore(userId, 3))
                .twoStarCount(ratingRepository.countByRevieweeIdAndScore(userId, 2))
                .oneStarCount(ratingRepository.countByRevieweeIdAndScore(userId, 1))
                .build();
    }

    // ========== ADMIN MODERATION ==========

    @Override
    @Transactional(readOnly = true)
    public Page<RatingDTO> getPendingReviewRatings(Pageable pageable) {
        return ratingRepository.findByStatus(RatingStatus.PENDING_REVIEW, pageable)
                .map(ratingMapper::toDTO);
    }

    @Override
    @Transactional
    public RatingDTO approveRating(Long ratingId, Long adminId, String adminNote) {
        Rating rating = ratingRepository.findById(ratingId)
                .orElseThrow(() -> new NotFoundException("Rating not found"));

        if (rating.getStatus() != RatingStatus.PENDING_REVIEW) {
            throw new BadRequestException("Rating is not pending review");
        }

        User admin = userRepository.findById(adminId)
                .orElseThrow(() -> new NotFoundException("Admin not found"));

        rating.setStatus(RatingStatus.APPROVED);
        rating.setReviewedBy(admin);
        rating.setReviewedAt(LocalDateTime.now());
        rating.setVisibleAt(LocalDateTime.now());
        rating.setAdminNote(adminNote);
        rating = ratingRepository.save(rating);

        log.info("Rating {} approved by admin {}", ratingId, adminId);
        return ratingMapper.toDTO(rating);
    }

    @Override
    @Transactional
    public RatingDTO flagRating(Long ratingId, Long adminId, String adminNote) {
        Rating rating = ratingRepository.findById(ratingId)
                .orElseThrow(() -> new NotFoundException("Rating not found"));

        if (rating.getStatus() != RatingStatus.PENDING_REVIEW) {
            throw new BadRequestException("Rating is not pending review");
        }

        User admin = userRepository.findById(adminId)
                .orElseThrow(() -> new NotFoundException("Admin not found"));

        // FLAGGED = stays hidden permanently (admin deems it unfair)
        rating.setStatus(RatingStatus.FLAGGED);
        rating.setReviewedBy(admin);
        rating.setReviewedAt(LocalDateTime.now());
        rating.setAdminNote(adminNote != null ? adminNote : "Flagged as unfair by admin");
        rating = ratingRepository.save(rating);

        log.info("Rating {} flagged (hidden) by admin {} - reason: {}", ratingId, adminId, adminNote);
        return ratingMapper.toDTO(rating);
    }

    // ========== SCHEDULED TASKS ==========

    @Override
    @Transactional
    public void autoRevealExpiredPendingRatings() {
        LocalDateTime cutoff = LocalDateTime.now().minusDays(7);
        List<Rating> pending = ratingRepository.findPendingReviewOlderThan(cutoff);

        LocalDateTime now = LocalDateTime.now();
        for (Rating r : pending) {
            r.setStatus(RatingStatus.VISIBLE);
            r.setVisibleAt(now);
            r.setAdminNote("Auto-revealed after 7 days without admin review");
            ratingRepository.save(r);
            log.warn("Auto-revealed rating {} after 7 days (contract={}, score={})",
                    r.getRatingId(), r.getContract().getContractId(), r.getScore());
        }

        if (!pending.isEmpty()) {
            log.info("Auto-revealed {} pending rating(s)", pending.size());
        }
    }

    @Override
    @Transactional
    public void autoRateExpiredContracts() {
        LocalDateTime cutoff = LocalDateTime.now().minusDays(RATING_DEADLINE_DAYS);

        // Find all COMPLETED contracts where endAt is older than 30 days
        List<Contract> completedContracts = contractRepository.findAll().stream()
                .filter(c -> c.getStatus() == ContractStatus.COMPLETED)
                .filter(c -> c.getEndAt() != null && c.getEndAt().isBefore(cutoff))
                .toList();

        LocalDateTime now = LocalDateTime.now();
        int autoCreated = 0;

        for (Contract contract : completedContracts) {
            List<Rating> existingRatings = ratingRepository.findByContract_ContractId(contract.getContractId());

            // Skip if both already rated
            boolean clientRated = existingRatings.stream()
                    .anyMatch(r -> r.getReviewer().getUserId().equals(contract.getClient().getUserId()));
            boolean studentRated = existingRatings.stream()
                    .anyMatch(r -> r.getReviewer().getUserId().equals(contract.getStudent().getUserId()));

            if (clientRated && studentRated) continue;

            // Auto-create 5-star for missing ratings
            if (!clientRated) {
                Rating autoRating = Rating.builder()
                        .contract(contract)
                        .reviewer(contract.getClient())
                        .reviewee(contract.getStudent())
                        .score(5)
                        .comment("Auto-generated 5-star rating (no review submitted within 30 days)")
                        .status(RatingStatus.VISIBLE)
                        .isAutoGenerated(true)
                        .visibleAt(now)
                        .build();
                ratingRepository.save(autoRating);
                autoCreated++;
                log.info("Auto-created 5-star rating: client {} -> student {} (contract {})",
                        contract.getClient().getUserId(), contract.getStudent().getUserId(), contract.getContractId());
            }

            if (!studentRated) {
                Rating autoRating = Rating.builder()
                        .contract(contract)
                        .reviewer(contract.getStudent())
                        .reviewee(contract.getClient())
                        .score(5)
                        .comment("Auto-generated 5-star rating (no review submitted within 30 days)")
                        .status(RatingStatus.VISIBLE)
                        .isAutoGenerated(true)
                        .visibleAt(now)
                        .build();
                ratingRepository.save(autoRating);
                autoCreated++;
                log.info("Auto-created 5-star rating: student {} -> client {} (contract {})",
                        contract.getStudent().getUserId(), contract.getClient().getUserId(), contract.getContractId());
            }

            // If the other party's real rating was HIDDEN, apply visibility rules now
            applyVisibilityRules(contract.getContractId());
        }

        if (autoCreated > 0) {
            log.info("Auto-created {} 5-star rating(s) for expired contracts", autoCreated);
        }
    }
}
