package com.exe202.skillnest.entity;

import com.exe202.skillnest.enums.RatingStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "ratings", schema = "public", indexes = {
    @Index(name = "idx_rating_contract", columnList = "contract_id"),
    @Index(name = "idx_rating_reviewer", columnList = "reviewer_id"),
    @Index(name = "idx_rating_reviewee", columnList = "reviewee_id"),
    @Index(name = "idx_rating_status", columnList = "status")
}, uniqueConstraints = {
    @UniqueConstraint(name = "uk_rating_contract_reviewer", columnNames = {"contract_id", "reviewer_id"})
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Rating {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "rating_id")
    private Long ratingId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "contract_id", nullable = false)
    private Contract contract;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewer_id", nullable = false)
    private User reviewer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewee_id", nullable = false)
    private User reviewee;

    @Column(nullable = false)
    private Integer score;

    @Column(columnDefinition = "TEXT")
    private String comment;

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private RatingStatus status = RatingStatus.HIDDEN;

    @Builder.Default
    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false;

    @Column(name = "visible_at")
    private LocalDateTime visibleAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewed_by")
    private User reviewedBy;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @Column(name = "admin_note", columnDefinition = "TEXT")
    private String adminNote;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
